# Generated by Django 5.1 on 2025-07-03 01:37

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Username must be at least 3 characters long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                255, "Username must be 255 characters or fewer"
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that email address already exists."
                        },
                        help_text="Required. Valid email address for account verification.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_index=True,
                        help_text="Required. Your password must be at least 8 characters long.",
                        max_length=255,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_index=True,
                        help_text="Required. Your first name.",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "First name must be at least 1 character long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                255, "First name must be 255 characters or fewer"
                            ),
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True,
                        help_text="Required. Your last name.",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Last name must be at least 1 character long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                255, "Last name must be 255 characters or fewer"
                            ),
                        ],
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The date and time when the user joined.",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="The date and time when the user last logged in.",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_users",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Format: 10 digit number without country code",
                        max_length=20,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "Phone number must be 10 digits long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                10, "Phone number must be 10 digits long"
                            ),
                        ],
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True,
                        help_text="Street address, P.O. box, company name, c/o",
                        max_length=255,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, unit, building, floor, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City or town", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="ZIP or postal code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="India", help_text="Country", max_length=100
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture (optional)",
                        null=True,
                        upload_to="profile_pictures/",
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi"), ("mr", "Marathi")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "newsletter_subscription",
                    models.BooleanField(
                        default=False, help_text="Subscribe to our newsletter"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="users.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="users.customuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
